from fastapi import APIRouter, HTTPException
import pandas as pd
import time
from src.api.schemas import PatientInput, PredictionResponse, Explanation
from src.api.dependencies import app_state
from src.models.explain import get_local_explanation
from src.utils.logger import get_logger

router = APIRouter()
logger = get_logger("predict")

@router.post("/predict", response_model=PredictionResponse)
async def predict(patient: PatientInput):
    if not app_state.is_ready:
        raise HTTPException(status_code=503, detail="Model is not ready")
        
    start_time = time.time()
    
    try:
        input_dict = patient.dict()
        
        # Map string labels back to numeric for model
        from src.features.feature_schema import CATEGORY_MAPPING
        for col, mapping in CATEGORY_MAPPING.items():
            if col in input_dict:
                val = input_dict[col]
                # Reverse mapping
                rev_mapping = {v: k for k, v in mapping.items()}
                if val in rev_mapping:
                    input_dict[col] = rev_mapping[val]
                    
        # Construct DataFrame in exactly the canonical order
        df = pd.DataFrame([input_dict], columns=app_state.metadata["feature_order"])
        
        # Inference
        probability = float(app_state.model.predict_proba(df)[:, 1][0])
        threshold = float(app_state.threshold)
        prediction = 1 if probability >= threshold else 0
        prediction_label = "Disease Present" if prediction == 1 else "Disease Absent"
        
        # Risk band (application display categories only)
        if probability < threshold * 0.5:
            risk_band = "Low"
        elif probability < threshold:
            risk_band = "Moderate"
        else:
            risk_band = "High"
            
        pred_time = time.time()
        
        # Explanation
        local_exp = get_local_explanation(app_state.explainer, df, app_state.metadata["feature_order"])
        
        exp_time = time.time()
        
        logger.info(f"Prediction successful. Probability: {probability:.3f}. "
                    f"Pred Latency: {(pred_time - start_time)*1000:.1f}ms. "
                    f"Exp Latency: {(exp_time - pred_time)*1000:.1f}ms.")
        
        return PredictionResponse(
            prediction=prediction,
            prediction_label=prediction_label,
            risk_probability=probability,
            decision_threshold=threshold,
            risk_band=risk_band,
            explanation=Explanation(**local_exp),
            version=app_state.metadata["model_version"],
            disclaimer="This output is generated by an educational machine learning model and is not a medical diagnosis."
        )
    except Exception as e:
        import traceback
        logger.error(f"Inference error: {str(e)}\n{traceback.format_exc()}")
        raise HTTPException(status_code=500, detail=f"An error occurred during inference: {str(e)}")
